modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL=""
displayURL="https://minecraft.curseforge.com/projects/minecraftsweepingdetail" 
logoFile="broom_icon.png"
authors="Untrustedlife"
license="GPLv3"

[[mods]]
    modId="ulsliminexblocks"
    version="1.0"
    displayName="Uls Liminex Blocks"
    description="A mod specifically designed for my Z-Liminex modpack, created to streamline the process of adding eerie, atmospheric blocks for building liminal spaces and modern city structures. Plus, it makes these blocks available for others to use! This mod really shines when paired with Lost Cities, as I've ensured that all the blocks are fully compatible, allowing for even more surreal and unusual cityscapes."
    credits="Untrustedlife"

[[dependencies.ulsliminexblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"