modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL=""
displayURL="https://minecraft.curseforge.com/projects/minecraftsweepingdetail" 
logoFile="broom_icon.png"
authors="Untrustedlife"
license="GPLv3"

[[mods]]
    modId="ulsliminexblocks"
    version="1.5.1"
    displayName="Uls Liminex Blocks"
    description="A mod specifically designed for my Z-Liminex modpack that adds numerous new vanilla styled blocks for building eerie liminal and dreamlike spaces."
    credits="Untrustedlife"

[[dependencies.ulsliminexblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"